apiVersion: v2
appVersion: "1.0"
description: Family Private Law - Document Generator Service
name: prl-dgs
version: 0.0.11
dependencies:
    - name: java
      version: ~3.7.2
      repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
