java:
    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    keyVaults:
      prl:
        resourceGroup: prl
        secrets:
          - microservicekey-prl-dgs-api
          - docmosis-api-key
          - launchDarkly-sdk-key
          - AppInsightsInstrumentationKey
          - prl-cos-idam-client-secret
          - test-genericpassword
          - idam-solicitor-username
          - idam-solicitor-password
          - system-update-user-username
          - system-update-user-password
          - app-insights-connection-string
    environment:
      MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
      DOCMOSIS_SERVICE_DEV_MODE_FLAG: "true"
      PDF_TEST_ENABLED: "true"
      CCD_CASE_DOCS_AM_API: http://prl-ccd-definitions-pr-1991-cdam
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
      IDAM_S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
      DOCMOSIS_SERVICE_BASE_URL: "https://docmosis.aat.platform.hmcts.net"
      REFORM_SERVICE_NAME: "prl"
      REFORM_TEAM: "prl"
      AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "prl_cos_api"
      AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
