java:
    applicationPort: 4007
    aadIdentityName: prl
    ingressHost: "prl-dgs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    autoscaling:
      enabled: true
      maxReplicas: 9
      minReplicas: 6
      targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
    keyVaults:
      prl:
        resourceGroup: prl
        secrets:
          - microservicekey-prl-dgs-api
          - docmosis-api-key
          - launchDarkly-sdk-key
          - AppInsightsInstrumentationKey
          - prl-cos-idam-client-secret
          - test-genericpassword
          - idam-solicitor-username
          - idam-solicitor-password
          - system-update-user-username
          - system-update-user-password
    environment:
        AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DOCMOSIS_SERVICE_BASE_URL: "https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net"
        CCD_CASE_DOCS_AM_API: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        REFORM_SERVICE_NAME: "prl"
        REFORM_TEAM: "prl"
        AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "prl_cos_api"
        AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
